---
- name: Zeige OS-Info aller Hosts
  hosts: all
  gather_facts: yes
  tasks:
    - name: OS-Info anzeigen
      debug:
        msg: "{{ inventory_hostname }}: {{ ansible_distribution | default(ansible_system) }} {{ ansible_distribution_version | default(ansible_os_family) }}"
