---
- name: Initialize updates log
  hosts: all
  gather_facts: no
  pre_tasks:
    - name: Initialize updates_log_entry on controller
      set_fact:
        updates_log_entry: {}
      delegate_to: localhost
      run_once: true

- name: Update Linux servers
  hosts: linux
  gather_facts: yes
  become: yes
  vars_files:
    - vault.yml
  tasks:

    # Ubuntu/Debian Tasks
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Upgrade all packages (Ubuntu/Debian)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: ubuntu_updates
      when: ansible_facts['os_family'] == "Debian"

    # Fedora 42 Tasks via CLI (kein dnf5 Modul)
    - name: Update package cache (Fedora/RHEL)
      command: dnf -y makecache
      register: fedora_cache
      when: ansible_facts['os_family'] == "RedHat"

    - name: Upgrade all packages (Fedora/RHEL)
      command: dnf -y upgrade
      register: fedora_updates
      when: ansible_facts['os_family'] == "RedHat"

    - name: Autoremove unnecessary packages (Fedora/RHEL)
      command: dnf -y autoremove
      when: ansible_facts['os_family'] == "RedHat"

    # Reboot if kernel updated
    - name: Reboot if kernel upgraded
      reboot:
        reboot_timeout: 200
        test_command: whoami

    # Collect Linux updates for logging
    - name: Collect Linux updates for logging
      set_fact:
        updates_log_entry: >-
          {{
            updates_log_entry | combine({
              inventory_hostname: {
                'os': ansible_facts['os_family'],
                'updates': (ubuntu_updates.upgraded | default([])) + (fedora_updates.stdout_lines | default([]))
              }
            })
          }}
      delegate_to: localhost
      run_once: true
      when: ansible_facts['os_family'] in ["Debian", "RedHat"]

- name: Update Windows servers
  hosts: windows
  gather_facts: yes
  tasks:

    - name: Check for updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: windows_pending

    - name: Install updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
        reboot: yes
      register: windows_updates

    # Collect Windows updates for logging
    - name: Collect Windows updates for logging
      set_fact:
        updates_log_entry: "{{ updates_log_entry | combine({inventory_hostname: {'os': 'Windows', 'updates': windows_updates.updates | default([])}}) }}"
      delegate_to: localhost
      run_once: true

- name: Write updates log to JSON file on controller with timestamp
  hosts: localhost
  gather_facts: no
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    log_file: "/tmp/all_updates_log_{{ timestamp }}.json"
  tasks:
    - name: Save all updates to timestamped JSON
      copy:
        dest: "{{ log_file }}"
        content: "{{ updates_log_entry | to_nice_json }}"
