---
- name: Update Linux and Windows systems
  hosts: all
  gather_facts: yes
  become: false  # verhindert sudo schon beim "Gathering Facts"

  vars:
    update_type: "Unbekannt"
    update_status: "n/a"
    reboot_required: "nein"

  tasks:
    # --------------------------
    # Linux: APT
    # --------------------------
    - name: Update APT-based Linux systems
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      register: apt_result
      when:
        - ansible_os_family != "Windows"
        - ansible_pkg_mgr is defined
        - ansible_pkg_mgr == "apt"
      become: yes

    - name: Set log vars for APT
      ansible.builtin.set_fact:
        update_type: "APT"
        update_status: "{{ 'changed' if apt_result.changed else 'ok' }}"
      when:
        - ansible_os_family != "Windows"
        - ansible_pkg_mgr is defined
        - ansible_pkg_mgr == "apt"

    # --------------------------
    # Linux: DNF5
    # --------------------------
    - name: Update all packages via DNF5
      ansible.builtin.shell: dnf -y upgrade
      register: dnf5_result
      changed_when: >
        (dnf5_result.stdout is defined and ('Nothing to do.' not in dnf5_result.stdout))
        or (dnf5_result.stderr is defined and ('Nothing to do.' not in dnf5_result.stderr))
      when:
        - ansible_os_family != "Windows"
        - ansible_pkg_mgr is defined
        - ansible_pkg_mgr == "dnf5"
      become: yes

    - name: Set log vars for DNF5
      ansible.builtin.set_fact:
        update_type: "DNF5"
        update_status: "{{ 'changed' if dnf5_result.changed else 'ok' }}"
      when:
        - ansible_os_family != "Windows"
        - ansible_pkg_mgr is defined
        - ansible_pkg_mgr == "dnf5"

    # --------------------------
    # Linux: Zypper (braucht community.general)
    # --------------------------
    - name: Update Zypper-based Linux systems
      community.general.zypper:
        name: "*"
        state: latest
      register: zypper_result
      when:
        - ansible_os_family != "Windows"
        - ansible_pkg_mgr is defined
        - ansible_pkg_mgr == "zypper"
      become: yes

    - name: Set log vars for Zypper
      ansible.builtin.set_fact:
        update_type: "Zypper"
        update_status: "{{ 'changed' if zypper_result.changed else 'ok' }}"
      when:
        - ansible_os_family != "Windows"
        - ansible_pkg_mgr is defined
        - ansible_pkg_mgr == "zypper"

    # --------------------------
    # Windows Updates (ohne FQCN)
    # --------------------------
    - name: Check for available updates (Windows)
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: searched
      register: win_updates_search
      when: ansible_os_family == "Windows"

    - name: Install Windows updates (Windows)
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
      register: win_update_result
      when: ansible_os_family == "Windows"

    - name: Set log vars for Windows
      ansible.builtin.set_fact:
        update_type: "WindowsUpdate"
        update_status: "{{ 'changed' if win_update_result.changed else 'ok' }}"
        reboot_required: "{{ 'ja' if win_update_result.reboot_required else 'nein' }}"
      when: ansible_os_family == "Windows"

    # --------------------------
    # Build log line
    # --------------------------
    - name: Build update log line
      ansible.builtin.set_fact:
        update_log_line: >-
          {{ ansible_date_time.date }} {{ ansible_date_time.time }},
          {{ inventory_hostname }},
          {{ ansible_distribution | default('n/a') }} {{ ansible_distribution_version | default('n/a') }},
          {{ update_type }},
          {{ update_status }},
          {{ reboot_required }}

    # --------------------------
    # Local log file handling (Linux)
    # --------------------------
    - name: Ensure local CSV exists (Linux)
      ansible.builtin.file:
        path: /var/log/ansible_updates.csv
        state: touch
        mode: '0644'
      become: yes
      when: ansible_os_family != "Windows"

    - name: Add CSV header if file is empty (Linux)
      ansible.builtin.shell: |
        if [ ! -s /var/log/ansible_updates.csv ]; then
          echo "Datum,Uhrzeit,Host,OS,Update-Typ,Status,Reboot-Erforderlich" > /var/log/ansible_updates.csv
        fi
      args:
        executable: /bin/bash
      become: yes
      when: ansible_os_family != "Windows"

    - name: Append update log to local CSV (Linux)
      ansible.builtin.lineinfile:
        path: /var/log/ansible_updates.csv
        line: "{{ update_log_line | regex_replace('\\s*,\\s*', ',') }}"
        create: yes
        insertafter: EOF
      become: yes
      when: ansible_os_family != "Windows"

    # --------------------------
    # Local log file handling (Windows) (ohne FQCN)
    # --------------------------
    - name: Ensure local CSV exists (Windows)
      win_file:
        path: C:\ansible_updates.csv
        state: touch
      when: ansible_os_family == "Windows"

    - name: Add CSV header if file is empty (Windows)
      win_shell: |
        if (!(Test-Path C:\ansible_updates.csv) -or (Get-Content C:\ansible_updates.csv).Length -eq 0) {
          "Datum,Uhrzeit,Host,OS,Update-Typ,Status,Reboot-Erforderlich" | Out-File -FilePath C:\ansible_updates.csv -Encoding utf8
        }
      when: ansible_os_family == "Windows"

    - name: Append update log to local CSV (Windows)
      win_lineinfile:
        path: C:\ansible_updates.csv
        line: "{{ update_log_line | regex_replace('\\s*,\\s*', ',') }}"
        create: yes
        insertafter: EOF
      when: ansible_os_family == "Windows"
