---
- name: Update Linux servers
  hosts: linux
  gather_facts: yes
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Update Package cache
      package:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      package:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Reboot if kernel upgraded
      reboot:
        reboot_timeout: 200
        test_command: whoami

    - name: Check for further updates
      package:
        update_cache: yes
        upgrade: yes
      register: ubuntu_updates

    - name: Show available updates
      debug:
        msg: "{{ ubuntu_updates }}"

- name: Update Windows servers
  hosts: windows
  gather_facts: yes
  tasks:

    - name: Check for updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: windows_pending

    - name: Install updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
        reboot: yes
      register: windows_updates

    - name: Show installed updates
      debug:
        msg: "{{ windows_updates }}"
