---
- name: Update Linux and Windows systems
  hosts: all
  gather_facts: yes
  vars:
    windows_reboot: yes

  tasks:
    # --------------------------
    # LINUX-UPDATES
    # --------------------------
    - name: Update APT-based Linux systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      become: yes
      register: apt_result

    - name: Show APT update result
      debug:
        var: apt_result
      when: ansible_os_family == "Debian"

    - name: Update YUM/DNF-based Linux systems
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      become: yes
      register: yum_result

    - name: Show YUM/DNF update result
      debug:
        var: yum_result
      when: ansible_os_family == "RedHat"

    - name: Update Zypper-based Linux systems
      zypper:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == "zypper"
      become: yes
      register: zypper_result

    - name: Show Zypper update result
      debug:
        var: zypper_result
      when: ansible_pkg_mgr == "zypper"

    # --------------------------
    # WINDOWS-UPDATES
    # --------------------------
    - name: Install Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: "{{ windows_reboot }}"
      when: ansible_os_family == "Windows"
      register: win_result

    - name: Show Windows update result
      debug:
        var: win_result
      when: ansible_os_family == "Windows"
