---
- name: Update Linux and Windows systems
  hosts: all
  gather_facts: yes
  become: yes  # Für Linux Root-Rechte

  tasks:
    - name: Update Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update RedHat/CentOS/Fedora systems
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update Windows systems
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      when: ansible_os_family == "Windows"
