---
- name: Update Linux servers
  hosts: linux
  gather_facts: yes
  become: yes
  vars_files:
    - vault.yml
  tasks:

    # Ubuntu/Debian Tasks
    - name: Update package cache (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Upgrade all packages (Ubuntu/Debian)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_facts['os_family'] == "Debian"

    # Fedora/RHEL Tasks
    - name: Check if dnf5 is installed
      stat:
        path: /usr/bin/dnf5
      register: dnf5_installed
      when: ansible_facts['os_family'] == "RedHat"

    - name: Set package manager for Fedora
      set_fact:
        fedora_pkg_manager: "{{ 'dnf-legacy' if dnf5_installed.stat.exists else 'dnf' }}"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Update package cache (Fedora/RHEL)
      command: "{{ fedora_pkg_manager }} -y makecache"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Upgrade all packages (Fedora/RHEL)
      command: "{{ fedora_pkg_manager }} -y upgrade"
      when: ansible_facts['os_family'] == "RedHat"

    - name: Reboot if kernel upgraded
      reboot:
        reboot_timeout: 200
        test_command: whoami

    - name: Collect Linux updates for logging
      set_fact:
        updates_log_entry: >-
          {{
            updates_log_entry | default({}) | combine({
              inventory_hostname: {
                'os': ansible_facts['os_family'],
                'updates': (ubuntu_updates.upgraded | default([])) + (fedora_updates.updates | default([]))
              }
            })
          }}
      delegate_to: localhost
      run_once: true
      when: ansible_facts['os_family'] in ["Debian", "RedHat"]

- name: Update Windows servers
  hosts: windows
  gather_facts: yes
  tasks:

    - name: Check for updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: windows_pending

    - name: Install updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
        reboot: yes
      register: windows_updates

    - name: Collect Windows updates for logging
      set_fact:
        updates_log_entry: "{{ updates_log_entry | default({}) | combine({inventory_hostname: {'os': 'Windows', 'updates': windows_updates.updates | default([])}}) }}"
      delegate_to: localhost
      run_once: true

- name: Write updates log to JSON file on controller with timestamp
  hosts: localhost
  gather_facts: no
  vars:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    log_file: "/tmp/all_updates_log_{{ timestamp }}.json"
  tasks:
    - name: Save all updates to timestamped JSON
      copy:
        dest: "{{ log_file }}"
        content: "{{ updates_log_entry | to_nice_json }}"
