---
- name: Update Linux and Windows systems
  hosts: all
  gather_facts: yes
  vars:
    windows_reboot: yes

  tasks:
    # --------------------------
    # Debian/Ubuntu
    # --------------------------
    - name: Update APT-based Linux systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      become: yes
      register: apt_result

    - name: Show APT update result
      debug:
        var: apt_result
      when: ansible_os_family == "Debian"

    # --------------------------
    # RHEL/CentOS (yum)
    # --------------------------
    - name: Update RHEL/CentOS systems with yum
      yum:
        name: "*"
        state: latest
      when: ansible_distribution in ["RedHat", "CentOS", "Rocky", "AlmaLinux"] and ansible_distribution_major_version | int < 9
      become: yes
      register: yum_result

    - name: Show YUM update result
      debug:
        var: yum_result
      when: ansible_distribution in ["RedHat", "CentOS", "Rocky", "AlmaLinux"] and ansible_distribution_major_version | int < 9

    # --------------------------
    # Fedora 42+ (dnf via shell)
    # --------------------------
    - name: Update Fedora 42+ systems using shell
      ansible.builtin.shell: dnf -y upgrade
      when: ansible_distribution == "Fedora" and ansible_distribution_major_version | int >= 42
      become: yes
      register: dnf_shell_result

    - name: Show DNF shell result
      debug:
        var: dnf_shell_result
      when: ansible_distribution == "Fedora" and ansible_distribution_major_version | int >= 42

    # --------------------------
    # openSUSE/SLE
    # --------------------------
    - name: Update Zypper-based Linux systems
      zypper:
        name: "*"
        state: latest
      when: ansible_os_family == "Suse"
      become: yes
      register: zypper_result

    - name: Show Zypper update result
      debug:
        var: zypper_result
      when: ansible_os_family == "Suse"

    # --------------------------
    # Windows
    # --------------------------
    - name: Install Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: "{{ windows_reboot }}"
      when: ansible_os_family == "Windows"
      register: win_result

    - name: Show Windows update result
      debug:
        var: win_result
      when: ansible_os_family == "Windows"
