---
- name: Uptime aller Hosts (kompakt, kein Python nötig)
  hosts: all
  gather_facts: no
  tasks:

    # Linux-Uptime
    - name: Linux-Uptime abfragen
      command: uptime
      register: linux_uptime
      ignore_errors: yes
      when: ansible_system is not defined or ansible_system != "Windows"

    - name: Linux-Uptime anzeigen
      debug:
        msg: "{{ inventory_hostname }}: {{ linux_uptime.stdout }}"
      when: linux_uptime is defined and linux_uptime.stdout is defined

    # Windows-Uptime
    - name: Windows-Uptime abfragen
      win_shell: Get-Uptime
      register: windows_uptime
      ignore_errors: yes
      when: ansible_connection == "winrm"

    - name: Windows-Uptime anzeigen
      debug:
        msg: "{{ inventory_hostname }}: {{ windows_uptime.stdout }}"
      when: windows_uptime is defined and windows_uptime.stdout is defined
